"""Persistence models for the market service."""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from enum import StrEnum

from sqlalchemy import (
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from core.database import Base


def _utcnow() -> datetime:
    return datetime.now(UTC)


class MarketStatus(StrEnum):
    """The part of the lifecycle [1.1] #1 owns.

    DRAFT is a scratchpad the creator's browser writes to on an idle timer.
    SUBMITTED means the creator pressed the button and every rule passed, so
    the terms are complete and internally consistent. Neither is visible to a
    trader: publishing to OPEN is [1.3] #3, and CLOSED, PENDING_RESOLUTION and
    RESOLVED arrive with [F-4] #44 and epic 3. Members are added here as those
    land, which is why this is stored as a VARCHAR with a CHECK rather than a
    native Postgres enum.
    """

    DRAFT = "draft"
    SUBMITTED = "submitted"


_STATUS_COLUMN = Enum(
    MarketStatus,
    name="market_status",
    native_enum=False,
    length=24,
    values_callable=lambda enum: [member.value for member in enum],
)


class Market(Base):
    __tablename__ = "markets"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)

    # Names a row in auth.users, and cannot be a foreign key: market_svc has no
    # grant on the auth schema, by design. The value is taken from the `sub`
    # claim of a signature-checked token, never from the request body, so it is
    # as trustworthy as the token is. The cost is that this service cannot tell
    # a deleted account from a live one; see ADR 0003.
    creator_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False, index=True)

    # Generated by the browser when the create form opens and sent on every
    # autosave, which is what makes POST /markets an upsert instead of a
    # machine for producing one abandoned draft every three seconds. Unique per
    # creator rather than globally, so a collision between two clients cannot
    # let one administrator write over another's market.
    draft_key: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)

    status: Mapped[MarketStatus] = mapped_column(
        _STATUS_COLUMN, nullable=False, default=MarketStatus.DRAFT,
        server_default=MarketStatus.DRAFT.value, index=True,
    )

    # Every term below is nullable because a draft is allowed to be incomplete.
    # An autosave that fired on a half-typed form and lost the admin's work
    # would defeat the point of autosaving. The rules in service/validation.py
    # are what enforce completeness, and only at the moment of submission.
    question: Mapped[str | None] = mapped_column(String(500), nullable=True)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)

    close_time: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    resolution_time: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    # How the sources below decide the winner. A bare URL says where to look
    # and not what to look for, and that gap is what [3.3] #11's dispute window
    # exists to absorb.
    resolution_criteria: Mapped[str | None] = mapped_column(Text, nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        server_default=func.now(),
        onupdate=_utcnow,
    )
    submitted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    outcomes: Mapped[list[MarketOutcome]] = relationship(
        back_populates="market",
        cascade="all, delete-orphan",
        lazy="selectin",
        order_by="MarketOutcome.position",
    )
    resolution_sources: Mapped[list[ResolutionSource]] = relationship(
        back_populates="market",
        cascade="all, delete-orphan",
        lazy="selectin",
        order_by="ResolutionSource.position",
    )

    __table_args__ = (
        UniqueConstraint("creator_id", "draft_key", name="uq_markets_creator_draft_key"),
        # Serves the only list query this service runs: the caller's own
        # markets, newest activity first.
        Index("ix_markets_creator_updated", "creator_id", "updated_at"),
    )


class MarketOutcome(Base):
    """One tradeable outcome. Two of them is a binary market, more is categorical."""

    __tablename__ = "market_outcomes"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    market_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("markets.id", ondelete="CASCADE"), nullable=False, index=True
    )

    # Server-assigned from the order the client sent, so it cannot collide, and
    # so the outcome order the admin arranged survives a reload. [1.2] #2 needs
    # a stable order for uniform initial prices, and epic 3 needs one to name a
    # winner without relying on a label that could be edited.
    position: Mapped[int] = mapped_column(Integer, nullable=False)

    label: Mapped[str] = mapped_column(String(120), nullable=False)

    market: Mapped[Market] = relationship(back_populates="outcomes")

    __table_args__ = (
        UniqueConstraint("market_id", "position", name="uq_outcome_position"),
        # Note what is NOT here: a unique index on lower(label). Two blank rows
        # in a half-typed form would violate it, so autosave would start
        # failing exactly when the admin is mid-thought. Label uniqueness is a
        # submission rule instead, in service/validation.py.
    )


class ResolutionSource(Base):
    """Where a trader can go to check the outcome for themselves."""

    __tablename__ = "resolution_sources"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    market_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("markets.id", ondelete="CASCADE"), nullable=False, index=True
    )
    position: Mapped[int] = mapped_column(Integer, nullable=False)

    # 2048 is the practical ceiling browsers and proxies agree on.
    url: Mapped[str] = mapped_column(String(2048), nullable=False)
    label: Mapped[str | None] = mapped_column(String(120), nullable=True)

    market: Mapped[Market] = relationship(back_populates="resolution_sources")

    __table_args__ = (
        UniqueConstraint("market_id", "position", name="uq_source_position"),
    )
