"""The read model for `audit.admin_actions`. [4.3] #15

This service does not own this table. `sql/02-schemas.sql` creates it, the
superuser owns it, several services append to it, and `audit_svc` is the only
role that may read it. What follows is therefore a description of a table
somebody else defines, and the two have to be kept in step by hand until
[F-1] #41 brings Alembic.

It is mapped read-only, and there is no `create_all` in this service to issue
a CREATE TABLE from it. If these columns drift from the SQL, queries fail with
`column ... does not exist` rather than the table being quietly recreated in
the wrong shape.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, Index, String, Text, Uuid
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base


class AdminAction(Base):
    """One thing an administrator did, as it was true at the moment they did it."""

    __tablename__ = "admin_actions"

    # Generated by the writing service rather than by the database. That is
    # what lets a writer INSERT without holding SELECT: a server-side default
    # would need RETURNING to read the value back, and RETURNING is a read.
    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)

    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # Taken from the `sub` claim of a signature-checked token, never from a
    # request body, so it is exactly as trustworthy as the token is.
    actor_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)

    # Snapshots, not joins. This service has no grant on `auth.users` and never
    # will, so there is no read-time lookup to resolve a name — and the
    # snapshot is the more truthful record anyway: it says who they were when
    # they acted, which survives a rename, a demotion or a deleted account.
    actor_username: Mapped[str] = mapped_column(String(32), nullable=False)
    actor_role: Mapped[str] = mapped_column(String(16), nullable=False)

    # A plain string rather than an enum, and unconstrained in SQL. The
    # vocabulary lives in each writing service's code; see the note in
    # sql/02-schemas.sql for why a CHECK here would let a stale constraint
    # abort the very admin action it is meant to record.
    action_type: Mapped[str] = mapped_column(String(64), nullable=False)

    target_type: Mapped[str] = mapped_column(String(32), nullable=False)
    target_id: Mapped[uuid.UUID | None] = mapped_column(Uuid, nullable=True)
    target_label: Mapped[str | None] = mapped_column(Text, nullable=True)

    reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Whatever else that action type needs to be reconstructible later. Free
    # form because this table is append-only: a new action type recording a new
    # shape must not require an ALTER on the one table meant never to change.
    context: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    source_service: Mapped[str] = mapped_column(String(32), nullable=False)

    # Declared so the model states what the reads depend on. The SQL file
    # creates them; nothing here does.
    __table_args__ = (
        Index("ix_admin_actions_feed", "occurred_at", "id"),
        Index("ix_admin_actions_actor", "actor_id", "occurred_at", "id"),
        Index("ix_admin_actions_action_type", "action_type", "occurred_at", "id"),
    )
