"""The read model for `audit.admin_actions`. [4.3] #15

sql/02-schemas.sql defines the table (ADR 0006), so this mapping is kept in
step with it by hand, for good (ADR 0020); `test_entities.py` checks the two agree.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, Index, String, Text, Uuid
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base


class AdminAction(Base):
    """One thing an administrator did, as it was true at the moment they did it."""

    __tablename__ = "admin_actions"

    # Generated by the writer, not the database: reading back a server default
    # needs RETURNING, which needs SELECT, which writers do not hold.
    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True)

    occurred_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    # From the verified token's `sub`, never from a request body.
    actor_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)

    # Snapshots, not joins: there is no grant on auth.users, and a snapshot
    # records who they were when they acted, which survives a rename or demotion.
    actor_username: Mapped[str] = mapped_column(String(32), nullable=False)
    actor_role: Mapped[str] = mapped_column(String(16), nullable=False)

    # A plain string with no CHECK: a stale constraint would abort the admin
    # action it was meant to record. ADR 0006.
    action_type: Mapped[str] = mapped_column(String(64), nullable=False)

    target_type: Mapped[str] = mapped_column(String(32), nullable=False)
    target_id: Mapped[uuid.UUID | None] = mapped_column(Uuid, nullable=True)
    target_label: Mapped[str | None] = mapped_column(Text, nullable=True)

    reason: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Free-form, so a new action type needs no ALTER on a table meant never
    # to change.
    context: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    source_service: Mapped[str] = mapped_column(String(32), nullable=False)

    # Declared to state what the reads depend on; sql/02-schemas.sql creates them.
    __table_args__ = (
        Index("ix_admin_actions_feed", "occurred_at", "id"),
        Index("ix_admin_actions_actor", "actor_id", "occurred_at", "id"),
        Index("ix_admin_actions_action_type", "action_type", "occurred_at", "id"),
    )
